"""Example of auto black correction on/off"""
# Constants
# fmt: off
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR   = 60*SECONDS_PER_MINUTE
SECONDS_PER_DAY    = 24*SECONDS_PER_HOUR
SECONDS_PER_WEEK   = 7*SECONDS_PER_DAY
# fmt: on
# auto black correction
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE
SECONDS_PER_DAY = 24 * SECONDS_PER_HOUR
SECONDS_PER_WEEK = 7 * SECONDS_PER_DAY
